name: Build and Release BluRaviole Kernels

permissions:
  contents: write
  actions: write

on:
  workflow_dispatch:
    inputs:
      make_release:
        description: 'Do you want to create a release?'
        required: true
        type: boolean
        default: true
      test_release:
        description: 'Trigger a test release (skips build, uses dummy values)?'
        required: true
        type: boolean
        default: false
      kernelsu_variant:
        description: "Choose KernelSU (must be 'Next')"
        required: true
        type: string
        default: "Next"
      kernelsu_branch:
        description: "Choose ksu branch (must be 'Stable', 'Dev', or 'Other')"
        required: true
        type: string
        default: "Dev"
      kernelsu_branch_other:
        description: "If 'Other' is selected, specify your custom branch"
        required: false
        type: string
        default: ""
      kernelsu_commit_hash:
        description: "Specify the GitHub commit hash for KernelSU Next (leave blank for latest)"
        required: false
        type: string
      susfs_version:
        description: "Specify the SUSFS version"
        required: true
        type: string
        default: "v1.5.9"

env:
  BASE_VERSION: "1.5.9"
  REPO_OWNER: RiRiRawrZ615
  REPO_NAME: android_kernel_google_gs101
  KERNEL_VERSION: "5.10.209"
  STOCK_PATCH: "AP1A.240505.004"

jobs:
  build-kernel-gs101:
    if: ${{ !inputs.test_release }}
    uses: ./.github/workflows/kernel-gs101-5.10.yml
    secrets: inherit
    with:
      make_release: ${{ inputs.make_release }}
      kernelsu_variant: ${{ inputs.kernelsu_variant }}
      kernelsu_branch: ${{ inputs.kernelsu_branch }}
      kernelsu_branch_other: ${{ inputs.kernelsu_branch_other }}
      kernelsu_commit_hash: ${{ inputs.kernelsu_commit_hash }}
      susfs_version: ${{ inputs.susfs_version }}

  trigger-release:
    runs-on: ubuntu-latest
    needs: build-kernel-gs101
    if: ${{ inputs.make_release && !inputs.test_release }}
    env:
      REPO_OWNER: RiRiRawrZ615
      REPO_NAME: android_kernel_google_gs101
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: android-gs-bluraviole-5.10-android14-qpr2-monolithic
          fetch-depth: 1
          submodules: false

      - name: Verify repository
      
